version: "3.5"

services:
    firebase:
        container_name: fb_ingenieria_firebase
        build: .
        user: node
        command: sh -c '${DEPLOY_CMD}'
        working_dir: /usr/node/app
        volumes:
            - ./:/usr/node/app
        ports:
            - 8080:8080
            - 9005:9005
