version: '3.5'

services:
    firebase:
        container_name: fb_ingenieria_firebase
        build: ./firebase
        user: node
        command: sh -c '${DEPLOY_CMD}'
        volumes:
            - ./firebase:/usr/node/app
        # env_file: .env
        ports:
            - '${PORT}:${PORT}'
